import folder from "@/assets/ScalingView/Business/folder.svg";
import card from "@/assets/ScalingView/Business/card.svg";
import crown from "@/assets/ScalingView/Business/crown.svg";
import share from "@/assets/ScalingView/Business/share.svg";
import user from "@/assets/ScalingView/Business/user.svg";
import server from "@/assets/ScalingView/Business/server.svg";

export default [
  {
    img: folder,
    title: "Subscription-Based Model",
    text: "Brains operates on a subscription model, with blockchain startups paying a regular fee for full access to our intelligent agents.",
  },
  {
    img: card,
    title: "Transaction Fees",
    text: "We take a percentage-based fee from all transactions made through our system, which includes NFT purchases and sales, providing a steady revenue stream.",
  },
  {
    img: crown,
    title: "Premium Features",
    text: "Additional revenue is generated by offering users premium features and services, enhancing their experience and engagement with our platform.",
  },
  {
    img: share,
    title: "Affiliate Marketing",
    text: "By partnering with other businesses, we can earn a commission for any traffic or sales brought by our referrals, expanding our revenue sources.",
  },
  {
    img: user,
    title: "Partnerships",
    text: "Collaborating with social media platforms and other tech companies can open up new monetization opportunities, contributing to our overall revenue.",
  },
  {
    img: server,
    title: "Scalability",
    text: "Our business model is designed to scale as the user base grows. The user base and revenue will increase as more users join the blockchain and engage with our platform.",
  },
];
